# Generated by Django 4.2.29 on 2026-05-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userbase',
            managers=[
            ],
        ),
    ]
