# Generated by Django 4.2.29 on 2026-07-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_base', '0002_alter_userbase_managers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('_group', 'name')},
        ),
    ]
